def socket_set_position2():
    server_ip = "192.168.0.18"
    port = 12345
    socket_open(server_ip,port,"socket_0")

    socket_send_line("current_pos","socket_0")
    sleep(0.1)

    p_=get_actual_tcp_pose()
    i=0
    while (i<6):
        socket_send_int(p_[i]*10000)
        i=i+1
    end

    q_=get_actual_joint_positions()
    i=0
    while (i<6):
        socket_send_int(q_[i]*10000)
        i=i+1
    end

    socket_close("socket_0")
end