def socket_set_position1():
    server_ip = "192.168.0.18"
    port = 12345
    socket_open(server_ip,port,"socket_0")

    socket_send_line("req_data","socket_0")
    sleep(0.1)
    buf=socket_read_ascii_float(6,socket_name="socket_0", timeout=2)
    #p_rel = p[0,0,0.05,0,0,0]
    p_rel = p[buf[1],buf[2],buf[3],buf[4],buf[5],buf[6]]
    socket_close("socket_0")

    q_=get_actual_joint_positions()
    p_ready=get_forward_kin(q=q_,tcp=p_rel)

    movej(p_ready, a=1.2, v=0.1, t=0, r=0.0)
end