#! /bin/sh
### BEGIN INIT INFO
# Provides:          vnc
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop vnc server
### END INIT INFO

# Some things that run always
NAME=x11vnc
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/$NAME
LOGFILE=/var/log/$NAME
DAEMON_ARGS="-o $LOGFILE -loop -display :0 -nap -many -rfbauth /root/.vnc/passwd"
SCRIPTNAME=/etc/init.d/$NAME


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting VNC server "
    start-stop-daemon -b --start --quiet --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_ARGS
    ;;
  stop)
    echo "Stoping VNC server"
    pkill x11vnc
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop}"
    exit 1
    ;;
esac

exit 0

